# Generated by Django 4.2.2 on 2023-07-12 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zip', models.CharField(max_length=10)),
                ('role_position', models.CharField(max_length=200)),
                ('joined_date', models.DateField(null=True)),
                ('manager', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('markytics_email', models.EmailField(max_length=254)),
                ('manager_email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_performance', models.PositiveIntegerField()),
                ('behaviour', models.PositiveIntegerField()),
                ('deadlines', models.PositiveIntegerField()),
                ('positives', models.CharField(max_length=400)),
                ('negatives', models.CharField(max_length=400)),
                ('scope_of_improvement', models.CharField(max_length=400)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employees')),
            ],
        ),
    ]
